/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sigu.view;

import aplikasisigu.Home;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import sigu.controller.controllerBarangKeluar;
import sigu.controller.controllerBarangMasuk;
import sigu.db.koneksiDatabase;

/**
 *
 * @author Luky Mulana
 */
public class viewListDataBarangKeluar extends javax.swing.JFrame {

    /**
     * Creates new form viewListDataBarang
     */
    private Home ho;
    private DefaultTableModel modelDataListBarangKeluar;
    private String sql = "";
    
    public viewListDataBarangKeluar(Home ho) throws IOException {
        initComponents();
        
        this.ho = ho;
        
        modelDataListBarangKeluar = new DefaultTableModel();
        tabelListDataBarangKeluar.setModel(modelDataListBarangKeluar);
        modelDataListBarangKeluar.addColumn("Kode Barang");
        modelDataListBarangKeluar.addColumn("Nama Barang");
        modelDataListBarangKeluar.addColumn("Nama Kategori");
        modelDataListBarangKeluar.addColumn("ID Kategori");
        modelDataListBarangKeluar.addColumn("Nama Supplier");
        modelDataListBarangKeluar.addColumn("ID Supplier");
        modelDataListBarangKeluar.addColumn("Stok");
        modelDataListBarangKeluar.addColumn("Satuan");
        
        TableColumnModel tcm = tabelListDataBarangKeluar.getColumnModel();
        tcm.removeColumn(tabelListDataBarangKeluar.getColumnModel().getColumn(3));
        tcm.removeColumn(tabelListDataBarangKeluar.getColumnModel().getColumn(4));
        
        tampilDataListBarang("");
    }
    
    public void tampilDataListBarang(String data) throws IOException {
        modelDataListBarangKeluar.getDataVector().removeAllElements();
        modelDataListBarangKeluar.fireTableDataChanged();
        
        //kondisi pengecekan
        if (data.equals("")) {
            sql = "SELECT b.kode_barang, b.nama_barang, k.nama_kategori, k.kode_kategori, s.nama_supplier, s.kode_supplier,b.stok, b.satuan "
                + "from barang b, kategori k, supplier s where b.kode_kategori = k.kode_kategori "
                + "and b.kode_supplier = s.kode_supplier order by b.kode_barang asc";
            
            
        } else sql = "SELECT b.kode_barang, b.nama_barang, k.nama_kategori, k.kode_kategori, s.nama_supplier, s.kode_supplier,b.stok, b.satuan "
                + "from barang b, kategori k, supplier s where b.kode_kategori = k.kode_kategori "
                + "and b.kode_supplier = s.kode_supplier and b.kode_barang like '%"+data+"%' order by b.kode_barang asc";
        
        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while (res.next()) {
                Object[] hasil;
                hasil = new Object[8];
                hasil[0] = res.getString("kode_barang");
                hasil[1] = res.getString("nama_barang");
                hasil[2] = res.getString("nama_kategori");
                hasil[3] = res.getString("kode_kategori");
                hasil[4] = res.getString("nama_supplier");
                hasil[5] = res.getString("kode_supplier");
                hasil[6] = res.getString("stok");
                hasil[7] = res.getString("satuan");
                
                modelDataListBarangKeluar.addRow(hasil);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewListDataBarangKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListDataBarangKeluar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKodeBarangViewListDataBarangKeluar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 205, 205));

        tabelListDataBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelListDataBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListDataBarangKeluarMouseClicked(evt);
            }
        });
        tabelListDataBarangKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelListDataBarangKeluarKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListDataBarangKeluar);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 78, 78));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIST DATA BARANG");

        txtKodeBarangViewListDataBarangKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeBarangViewListDataBarangKeluarKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 78, 78));
        jLabel2.setText("Kode Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtKodeBarangViewListDataBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeBarangViewListDataBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeBarangViewListDataBarangKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeBarangViewListDataBarangKeluarKeyPressed
        try {
            // TODO add your handling code here:
            // fungsi ini akan di eksekusi ketika kita mencari nama barang
            tampilDataListBarang(txtKodeBarangViewListDataBarangKeluar.getText());
            
        } catch (IOException ex) {
            Logger.getLogger(viewListDataBarangKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtKodeBarangViewListDataBarangKeluarKeyPressed

    private void tabelListDataBarangKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelListDataBarangKeluarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelListDataBarangKeluarKeyPressed

    private void tabelListDataBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListDataBarangKeluarMouseClicked
        // TODO add your handling code here:
        int ambilRow = tabelListDataBarangKeluar.getSelectedRow();
        ho.getTfKodeBarangKeluar().setText((String) tabelListDataBarangKeluar.getValueAt(ambilRow, 0));
        ho.getTfNamaBarangKeluar().setText(tabelListDataBarangKeluar.getValueAt(ambilRow, 1).toString());
        ho.getTfSupplierBarangKeluar().setText(tabelListDataBarangKeluar.getValueAt(ambilRow, 3).toString());
        ho.getTfKodeSupplierBarangKeluar().setText(tabelListDataBarangKeluar.getModel().getValueAt(ambilRow, 5).toString());
                
        ho.getTfJumlahBarangKeluar().requestFocus();
        ho.setEnabled(true);
        controllerBarangKeluar cBK = new controllerBarangKeluar(ho);
        cBK.kontrolButtonTiga();
        this.dispose();
    }//GEN-LAST:event_tabelListDataBarangKeluarMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelListDataBarangKeluar;
    private javax.swing.JTextField txtKodeBarangViewListDataBarangKeluar;
    // End of variables declaration//GEN-END:variables
}
